### PR TITLE
Update metadata.json to support GNOME 46

### PR DESCRIPTION
**Pull request by Dritzii**

### CODE REVIEW

**Comment by jikamens** [comment]
I haven't had time to test on GNOME 46 yet. Have you tested? Does it work?

**Comment by mcilloni** [comment]
I tried to quickly update the extension to allow installation on 46 and it works fine (on Wayland). Never had a chance to test on Xorg though.

**Comment by jikamens** [comment]
Fair enough. ;-)

**Comment by jikamens** [comment]
Thanks for the patch, merged and uploaded to extensions.gnome.org.

**Pull request merged**
